apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bjqlwjbxm-dotnet-basic-gitops
  description: This is GitOps manifest for bjqlwjbxm-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bjqlwjbxm-dotnet-basic
    backstage.io/kubernetes-id: bjqlwjbxm-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/bjqlwjbxm-dotnet-basic-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bjqlwjbxm-dotnet-basic
